config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :games
  resources :posts

  root "pages#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :games, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.require(:game).permit(:image, :name, :description, :rating, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  # Unless the user is logged in, they can't view anything except the index and show variables
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order ("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render root_path, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  #test
  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  # Checks if the user is signed in
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  #   Triggers when the player tries to update account settings
  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="container">
  <h1>Games</h1>
  <style>
    td {
      text-align: center;
    }
  </style>
  <table>
    <thead>
    </thead>
  </div>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <div class="card">
          <div class="card-header">
            <img src=<%= game.image %> style="width:200px;height:auto;">
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= game.name %></h5>
            <p class="card-text">Rating: <%= game.rating %></p>
            <%if game.price == 0%>
              <p class="card-text">Price: Free to play</p>
            <% else %>
              <p class="card-text">Price: $<%= game.price %></p>
            <% end  %>
            <p class="card-text price"><%= game.created_at %></p>
            <a href="#" class="btn btn-primary"><%= link_to 'Show', game %></a>
          </div>
        </div>
        <%if user_signed_in? %>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Game' , new_game_path, class:"btn btn-dark" %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <img src=<%= @game.image %> style="width:200px;height:auto;">
</p>
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @game.rating %>
</p>
<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/pages/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Smoke</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="pages" href="/posts">Community</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/games">Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/pages">Profile</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/edit">Edit Profile</a>
          </li>
        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_up">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">Sign In</a>
          </li>
        <% end %>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success search" type="submit" style="visibility: hidden">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/posts/_feed.html.erb
<div class="box">
  <article class="media box">
    <figure class="media-left">
      <% @posts.each do | post | %>
        <div class="card">
          <div class="card-body">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/64x64.png" style="border-radius: 50%">
            </p>
            <h5 class="card-title"><%= post.user.name%></h5>
            <h6 class="card-subtitle mb-2 text-muted">@<%= post.user.username %></h6>
            <p class="card-text"><%= post.content %></p>
          </div>
        </div>
        <%if user_signed_in? && current_user.id == post.user_id %>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-dark btn-secondary btn-sm" %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post??' }, 
            class: "btn btn-dark btn-secondary btn-sm"  %>
            </div>
          </nav>
        <% end %>
      <%end%>
    </figure>
  </article>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <p id="notice"><%= notice %></p>
      <h1>Community</h1>
      <table>
        <% if user_signed_in? %>
          <div class="card-body">
            <p class="image is-64x64">
              <img src="https://bulma.io/images/placeholders/64x64.png" style="border-radius: 50%">
            </p>
            <h5 class="card-title"><%= current_user.name%></h5>
            <h6 class="card-subtitle mb-2 text-muted">@<%= current_user.username %></h6>
            <%= render "posts/form"%>
          </div>
        <% end%>
        <br>
        <%= render "posts/feed"%>
      </table>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>